name: city
path: "scenes/${scene.name}/${scene.name}.xml"
textures: ["scenes/${scene.name}/textures/${texture}.png"]
target_param_keys: ["mat-Mail box-perturb.brdf_0.base_color.data"]
sensor_key: "PerspectiveCamera"
sensor_radius: 3.0
sensor_count: 1024
sensor_z_lats: [0.6]
use_batch_sensor: false