name: city
path: "scenes/${scene.name}/${scene.name}.xml"
tex: "scenes/${scene.name}/textures/${texture}.png"
target_param_key: "mat-Mail box-perturb.brdf_0.base_color.data"
sensor_key: "PerspectiveCamera"