name: city_stop_sign
path: "scenes/${scene.name}/${scene.name}.xml"
textures: ["scenes/${scene.name}/textures/${texture}.png"]
target_param_keys: ["mat-Material.004.brdf_0.base_color.data"]
target_mesh: ["scenes/${scene.name}/meshes/stop_sign.ply"]
sensor_key: "PerspectiveCamera"
sensor_radius: 1.5
sensor_count: 9
resx: 256
resy: 256
sensor_z_lats: [0.0]
use_batch_sensor: true