name: forest_soldier
path: "scenes/${scene.name}/${scene.name}.xml"
textures: ["scenes/${scene.name}/textures/${texture}.png"]
target_param_keys: ["camo-Blend.weight.data","camo-Blend-1.weight.data", "camo-Blend-2.weight.data", "camo-Blend-3.weight.data","camo-Blend-1-2.weight.data"]
sensor_key: "PerspectiveCamera"
