name: mesa
path: "scenes/${scene.name}/${scene.name}.xml"
textures: ["scenes/${scene.name}/textures/${texture}.png"]
target_param_keys: ["mat-Material.005.brdf_0.base_color.data"]
target_mesh: ["scenes/${scene.name}/meshes/mesa_top.ply"]
sensor_key: "PerspectiveCamera"
sensor_radius: 400
sensor_count: 1
resx: 512
resy: 512
sensor_z_lats: [8]
use_batch_sensor: false