name: patio
path: "scenes/${scene.name}/${scene.name}.xml"
textures: ["scenes/${scene.name}/textures/${texture}.png"]
target_param_keys: ["mat-Material.001.brdf_0.base_color.data"]
sensor_key: "PerspectiveCamera"
sensor_radius: 2.41
sensor_count: 2
resx: 256
resy: 256
sensor_z_lats: [0.95]
use_batch_sensor: false