name: teapot_scene
path: "scenes/${scene.name}/${scene.name}.xml"
textures: ["scenes/${scene.name}/textures/noise_tex.png"]
target_param_keys: ["mat-Material.brdf_0.base_color.data"]
sensor_key: "PerspectiveCamera"