name: underwater
path: "scenes/${scene.name}/${scene.name}.xml"
textures: ["scenes/${scene.name}/textures/${texture}.png"]
target_param_keys: ["mat-tall_box_mat.brdf_0.base_color.data"]
target_mesh: ["scenes/${scene.name}/meshes/tall_box-Material.001.ply"]
sensor_key: "PerspectiveCamera"
sensor_radius: 8.0
sensor_count: 64
sensor_z_lats: [0.5]
use_batch_sensor: false